; INFO: pour récupérer les notices issues de xpac ou renseigner votre clé API, voir les lignes 64 et 71

append = pack
label = query-openalex-for-model
extension = json
mimeType = application/json

[use]
plugin = conditor
plugin = basics
plugin = analytics

[URLParse]

[env]

path = per-page
value = 200

path = include_xpac
value = true

path = sort
value = publication_date:desc

path = url
value = https://api.openalex.org/works

path = query
value = get("search")

path = labelizeBoolean
value = fix((bool)=> bool === true ? "Oui" : bool === false ? "Non" : "Inconnu")

path = cleanEscapedHtmlText
value = fix((str)=> \
  _.chain(str) \
    .thru(x => _.unescape(x)) \
    .replace(/&amp;/g, "&") \
    .replace(/&lt;/g, "<") \
    .replace(/&gt;/g, ">") \
    .replace(/&nbsp;/g, " ") \
    .replace(/&rsquo;/g, "'") \
    .replace(/\\t/g, " ") \
    .replace(/&(eacute|ecirc|egrave|Eacute|agrave|acirc|ocirc|oelig|iuml|ccedil|ucirc|uuml|ugrave);/g, \
             m => ({ \
               '&eacute;':'é','&ecirc;':'ê','&egrave;':'è','&Eacute;':'É','&agrave;':'à','&acirc;':'â', \
               '&ocirc;':'ô','&oelig;':'œ','&iuml;':'ï','&ccedil;':'ç','&ucirc;':'û','&uuml;':'ü','&ugrave;':'ù' \
             }[m] || m)) \
    .replace(/<[^>]+>/g, " ") \
    .replace(/\\n/g, " ") \
    .replace(/\s+/g, " ") \
    .trim() \
    .value() \
)

[exchange]
value = get("searchParams")

[assign]
path = per-page
value = env("per-page")

; Supprimez les ; des 2 lignes ci-dessous pour inclure les notices issues de XPAC
;path = include_xpac
;value = env('include_xpac')

path = sort
value = env("sort")

; Supprimez les ; des 2 lignes ci-dessous et ajoutez votre clé API dans value si vous souhaitez l'utiliser
;path = api_key
;value = ***********

[OAFetch]
url = env("url")
timeout = 60000
retries = 1

[assign]
path = uri
value = get("id").replace("https://openalex.org/", "").prepend("uid:/").trim()

path = doi
value = get("doi").replace("https://doi.org/","").toLower()

path = title
value = get("title").thru(env("cleanEscapedHtmlText"))

path = publication_year
value = get("publication_year").toString()

path = language
value = get("language").thru(lang => lang ? _.capitalize(new Intl.DisplayNames(["FR"], { type: "language"}).of(lang)) : "n/a")

path = source
value = get("primary_location.source.display_name")

path = open_access.is_oa
value = get("open_access.is_oa").thru(env("labelizeBoolean"))

path = open_access.oa_status
value = get("open_access.oa_status").capitalize()

path = has_fulltext
value = get("has_fulltext").thru(env("labelizeBoolean"))

path = is_retracted
value = get("is_retracted").thru(env("labelizeBoolean"))

path = is_paratext
value = get("is_paratext").thru(env("labelizeBoolean"))

path = is_xpac
value = get("is_xpac").thru(env("labelizeBoolean"))

path = sustainable_development_goals
value = get("sustainable_development_goals").map( item => `Goal ${item.id.match(/\/sdg\/(\d+)/)[1]} : ${item.display_name}`).thru(arr => _.isEmpty(arr) ? ["No sustainable development goal"] : arr)

[assign]
path = authorsInstitutionsTree
value = get("authorships", []) \
  .castArray() \
  .map(a => \
    [ \
      [ a.author && a.author.display_name ], \
      _.chain(a.institutions || []) \
        .map(i => i && i.display_name) \
        .without(null, undefined, "") \
        .uniq() \
        .thru(insts => insts.length === 0 ? ["n/a"] : insts) \
        .value() \
    ] \
  )

path = uniqFlattenInstitutions
value = get("authorships").flatMap("institutions").map("display_name").uniq()

path = is_hal
value = get("locations").map("landing_page_url").compact().some(item=>(/[^a-zA-Z0-9]hal[^a-zA-Z0-9]/).test(item)).thru(env("labelizeBoolean"))

path = nonRepositorySource
value = get("primary_location.source").thru(obj =>obj && obj.type !=="repository" && self.primary_location.version === "publishedVersion" ? obj :{display_name:"n/a"}).get("display_name")

path = topLevelPublisher
value = get("primary_location.source.host_organization_lineage_names", []) \
  .castArray() \
  .without("n/a", null, undefined, "") \
  .uniq() \
  .without( \
    "Springer Science+Business Media", \
    "Vandenhoeck & Ruprecht", \
    "University of California, Berkeley", \
    "University of California, Los Angeles", \
    "Siberian Branch of the Russian Academy of Sciences" \
  ) \
  .thru(lineage => \
    lineage.length === 0 \
      ? ["n/a"] \
      : lineage.length === 1 \
        ? lineage \
        : _.xor( \
            [ self.primary_location.source.host_organization_name ], \
            lineage \
          ) \
  ) \
  .thru(arr => _.first(arr))

[assign]
path = nonRepositoryTopLevelPublisher
value = get("nonRepositorySource").thru(so => so !=="n/a" ? self.topLevelPublisher : so)

path = indexed_in_hal_enriched
value = get("indexed_in").concat(self.is_hal).without("Non").map(item=>item === "Oui" ? "hal" : item).sort()

path = codes_iso2
value = get("authorships").flatMap("countries").filter(d => _.isString(d) && d.length === 2).uniq()

path = countries
value = get("authorships").flatMap("countries").filter(d => _.isString(d) && d.length === 2).map(d => new Intl.DisplayNames(["FR"], { type: "region"}).of(d))

[assign]
path = collaborationCountries
value = get("countries").uniq().thru(array => _.size(array) >=2 ? array : [])

path = hasInternationalCollaboration
value = get("countries").uniq().thru(array => _.size(array) >=2 ? "Oui" : "Non")

path = abstract
value = get("abstract_inverted_index").flatMap((values, key) => values.map(value => [value, key])) \
  .sort((a, b) => a[0] - b[0]) \
  .map(item => item[1]) \
  .join(" ") \
  .thru(env("cleanEscapedHtmlText"))

path = importedDate
value = fix(new Date()).thru(d => new Intl.DateTimeFormat("fr-FR", { year: "numeric", month: "long", day: "numeric" }).format(d))

path = query
value = env("query").thru(q => decodeURIComponent(q))

path = importDateTime
value = fix(new Date()).thru(d => \
  new Intl.DateTimeFormat("fr-FR", { \
    timeZone: "Europe/Paris", \
    year: "numeric", \
    month: "long", \
    day: "numeric", \
    hour: "2-digit", \
    minute: "2-digit", \
    second: "2-digit" \
  }).format(d) \
)

[exchange]
value = omit(["abstract_inverted_index"])

; Ensures that each object contains an identification key (required by lodex)
[swing]
test = pick(["URI", "uri"]).pickBy(_.identity).isEmpty()
[swing/identify]

; Ignore objects with duplicate URI
[dedupe]
ignore = true

; Prevent keys from containing dot path notation (which is forbidden by nodejs mongoDB driver)
[OBJFlatten]
separator = fix(".")
reverse = true
safe = true

; Uncomment to see in server logs, each data sent to the database
;[debug]