FROM node:12-alpine

WORKDIR /app
COPY ./package.json ./package-lock.json /app
RUN npm install --production && \
    npm cache clean --force

COPY ./scripts /app/scripts

EXPOSE 31976
CMD ["npx", "ezs", "-d", "/app/scripts"]
