version: "2"

services:
    hub:
        image: selenium/hub:3.4.0

    chromedebug:
        image: selenium/node-chrome-debug:3.4.0
        volumes:
            - .:/app
        working_dir: /app
        links:
            - hub
            - api
        environment:
            http_proxy:  ${http_proxy}
            https_proxy: ${https_proxy}
            no_proxy: "localhost,127.0.0.1,api,hub"
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        ports:
            - 5900:5900

    api:
        image: node:7.8.0
        volumes:
            - .:/app
        working_dir: /app
        environment:
            http_proxy:  ${http_proxy}
            https_proxy: ${https_proxy}
            NODE_APP_INSTANCE: test
            NODE_ENV: test
            no_proxy: "localhost,127.0.0.1,api,hub"
        links:
            - mongo
        depends_on:
            - mongo
        command: node --harmony-async-await --require babel-register ./src/api

    mongo:
        image: mongo:3.0.14
        command: "--smallfiles"
        ports:
            - 27017:27017

