import advancedNetwork from './chart/advancedNetwork';
import asterPlotChart from './chart/asterPlotChart';
import bubbleChart from './chart/bubbleChart';
import clusteredChart from './chart/clustered-chart';
import directed3DNetwork from './chart/directed3DNetwork';
import directedNetwork from './chart/directedNetwork';
import fieldClone from './chart/fieldClone';
import hierarchicalTree from './chart/hierarchical-tree';
import leaflet from './chart/leaflet';
import network from './chart/network';
import network3D from './chart/network3D';
import parallelCoordinatesChart from './chart/parallel-coordinates';
import streamgraph from './chart/streamgraph';
import venn from './chart/venn';
import lodexField from './lodex/field';
import resource from './lodex/resource';
import backButton from './other/back-button';
import istex from './other/istex';
import istexCitation from './other/istexCitation';
import istexRefbibs from './other/istexRefbibs';
import istexSummary from './other/istexSummary';
import json from './other/json';
import resourcesGrid from './other/resources-grid';
import paginatedTable from './other/table/paginated';
import unpaginatedTable from './other/table/unpaginated';
import code from './text/code';
import ejs from './text/ejs';
import emphasedNumber from './text/emphased-number';
import html from './text/html';
import identifierBadge from './text/identifier-badge';
import latex from './text/latex';
import list from './text/list';
import markdownModal from './text/markdown/modal';
import markdown from './text/markdown/simple';
import paragraph from './text/paragraph';
import sentence from './text/sentence';
import sparqlTextField from './text/sparql/SparqlTextField';
import title from './text/title';
import email from './url/email';
import iframe from './url/iframe';
import image from './url/image';
import link from './url/link';
import linkImage from './url/link-image';
import pdf from './url/pdf';
import redirect from './url/redirect';
import uri from './url/uri';
import vegaLite from './vega-lite';
import globalBarchart from './vega-lite/component/bar-chart';
import bubblePlot from './vega-lite/component/bubble-plot';
import cartography from './vega-lite/component/cartography';
import heatmap from './vega-lite/component/heatmap';
import globalPiechart from './vega-lite/component/pie-chart';
import flowMap from './vega/component/flow-map';
import globalRadarchart from './vega/component/radar-chart';
import TreeMap from './vega/component/tree-map';

export const FORMATS_CATALOG = [
    {
        name: 'formatAsterPlotChart',
        description: 'formatAsterPlotChartDescription',
        componentName: 'asterPlotChart',
        component: asterPlotChart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-aster-plot',
        isUrlValue: false,
    },
    {
        name: 'formatCode',
        description: 'formatCodeDescription',
        componentName: 'code',
        component: code,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-code',
        isUrlValue: false,
    },
    {
        name: 'formatGlobalBarchart',
        description: 'formatGlobalBarchartDescription',
        componentName: 'globalBarchart',
        component: globalBarchart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-diagramme-en-barres',
        isUrlValue: false,
    },
    {
        name: 'formatGlobalPiechart',
        description: 'formatGlobalPiechartDescription',
        componentName: 'globalPiechart',
        component: globalPiechart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-diagramme-circulaire',
        isUrlValue: false,
    },
    {
        name: 'formatGlobalRadarchart',
        description: 'formatGlobalRadarchartDescription',
        componentName: 'globalRadarchart',
        component: globalRadarchart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-diagramme-radar',
        isUrlValue: false,
    },
    {
        name: 'formatTreemap',
        description: 'formatTreemapDescription',
        componentName: 'Treemap',
        component: TreeMap,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-graphique-hi%C3%A9rarchique',
        isUrlValue: false,
    },
    {
        name: 'formatEmphasedNumber',
        description: 'formatEmphasedNumberDescription',
        componentName: 'emphasedNumber',
        component: emphasedNumber,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-chiffre-en-gras',
        isUrlValue: false,
    },
    {
        name: 'formatIdentifierBadge',
        description: 'formatIdentifierBadgeDescription',
        componentName: 'identifierBadge',
        component: identifierBadge,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-badge-pour-identifiant',
        isUrlValue: false,
    },
    {
        name: 'formatEmail',
        description: 'formatEmailDescription',
        componentName: 'email',
        component: email,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#url-lien-courriel',
        isUrlValue: false,
    },
    {
        name: 'formatFieldClone',
        description: 'formatFieldCloneDescription',
        componentName: 'fieldClone',
        component: fieldClone,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#copie-d%E2%80%99un-champ-existant',
        isUrlValue: false,
    },
    {
        name: 'formatHtml',
        description: 'formatHtmlDescription',
        componentName: 'html',
        component: html,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-balises-html',
        isUrlValue: false,
    },
    {
        name: 'formatImage',
        description: 'formatImageDescription',
        componentName: 'image',
        component: image,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-url-d%E2%80%99une-image',
        isUrlValue: true,
    },
    {
        name: 'formatIFrame',
        description: 'formatIFrameDescription',
        componentName: 'iframe',
        component: iframe,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#iframe',
        isUrlValue: true,
    },
    {
        name: 'formatPdf',
        description: 'formatPdfDescription',
        componentName: 'pdf',
        component: pdf,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-url-d%E2%80%99un-pdf',
        isUrlValue: false,
    },
    {
        name: 'formatLatex',
        description: 'formatLatexDescription',
        componentName: 'latex',
        component: latex,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-latex',
        isUrlValue: true,
    },
    {
        name: 'formatEJS',
        description: 'formatEJSDescription',
        componentName: 'ejs',
        component: ejs,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/', // format missing from documentation
        isUrlValue: false,
    },
    {
        name: 'formatIstex',
        description: 'formatIstexDescription',
        componentName: 'istex',
        component: istex,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-requ%C3%AAte-istex',
        isUrlValue: true,
    },
    {
        name: 'formatLink',
        description: 'formatLinkDescription',
        componentName: 'link',
        component: link,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#url-lien-interne',
        isUrlValue: false,
    },
    {
        name: 'formatLinkImage',
        description: 'formatLinkImageDescription',
        componentName: 'linkImage',
        component: linkImage,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-lien-image',
        isUrlValue: true,
    },
    {
        name: 'formatList',
        description: 'formatListDescription',
        componentName: 'list',
        component: list,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-liste-de-valeurs',
        isUrlValue: false,
    },
    {
        name: 'formatMarkdown',
        description: 'formatMarkdownDescription',
        componentName: 'markdown',
        component: markdown,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-syntaxe-markdown',
        isUrlValue: false,
    },
    {
        name: 'formatMarkdownModal',
        description: 'formatMarkdownModalDescription',
        componentName: 'markdownModal',
        component: markdownModal,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-syntaxe-markdown',
        isUrlValue: false,
    },
    {
        name: 'formatUri',
        description: 'formatUriDescription',
        componentName: 'uri',
        component: uri,
        type: 'url',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#url-externe',
        isUrlValue: true,
    },
    {
        name: 'formatTitle',
        description: 'formatTitleDescription',
        componentName: 'title',
        component: title,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-titre',
        isUrlValue: false,
    },
    {
        name: 'formatParagraph',
        description: 'formatParagraphDescription',
        componentName: 'paragraph',
        component: paragraph,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-paragraphe',
        isUrlValue: false,
    },
    {
        name: 'formatParallelCoordinatesChart',
        description: 'formatParallelCoordinatesChartDescription',
        componentName: 'parallelCoordinatesChart',
        component: parallelCoordinatesChart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-coordonn%C3%A9es-parall%C3%A8les',
        isUrlValue: false,
    },
    {
        name: 'formatSentence',
        description: 'formatSentenceDescription',
        componentName: 'sentence',
        component: sentence,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#texte-phrase',
        isUrlValue: false,
    },
    {
        name: 'formatVegaLite',
        description: 'formatVegaLiteDescription',
        componentName: 'vegaLite',
        component: vegaLite,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-syntaxe-vega-lite',
        isUrlValue: false,
    },
    {
        name: 'formatResource',
        description: 'formatResourceDescription',
        componentName: 'resource',
        component: resource,
        type: 'lodex',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#lodex-ressource',
        isUrlValue: true,
    },
    {
        name: 'formatLodexField',
        description: 'formatLodexFieldDescription',
        componentName: 'lodexField',
        component: lodexField,
        type: 'lodex',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#lodex-champ',
        isUrlValue: true,
    },
    {
        name: 'formatResourcesGrid',
        description: 'formatResourcesGridDescription',
        componentName: 'resourcesGrid',
        component: resourcesGrid,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-grille-de-ressources',
        isUrlValue: true,
    },
    {
        name: 'formatPaginatedTable',
        description: 'formatPaginatedTableDescription',
        componentName: 'paginatedTable',
        component: paginatedTable,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-tableau-pagin%C3%A9',
        isUrlValue: true,
    },
    {
        name: 'formatUnpaginatedTable',
        description: 'formatUnpaginatedTableDescription',
        componentName: 'unpaginatedTable',
        component: unpaginatedTable,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-tableau-non-pagin%C3%A9',
        isUrlValue: true,
    },
    {
        name: 'formatBubblePlot',
        description: 'formatBubblePlotDescription',
        componentName: 'bubblePlot',
        component: bubblePlot,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-diagrammes-%C3%A0-bulles',
        isUrlValue: false,
    },
    {
        name: 'formatCartography',
        description: 'formatCartographyDescription',
        componentName: 'cartography',
        component: cartography,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-cartographie',
        isUrlValue: false,
    },
    {
        name: 'formatHeatmap',
        description: 'formatHeatmapDescription',
        componentName: 'heatmap',
        component: heatmap,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-carte-de-chaleur',
        isUrlValue: false,
    },
    {
        name: 'formatNetwork',
        description: 'formatNetworkDescription',
        componentName: 'network',
        component: network,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-r%C3%A9seaux',
        isUrlValue: false,
    },
    {
        name: 'formatNetwork3D',
        description: 'formatNetwork3DDescription',
        componentName: 'network3D',
        component: network3D,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-r%C3%A9seaux-3d',
        isUrlValue: false,
    },
    {
        name: 'formatAdvancedNetwork',
        description: 'formatAdvancedNetworkDescription',
        componentName: 'advancedNetwork',
        component: advancedNetwork,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-r%C3%A9seaux-avance',
        isUrlValue: false,
    },
    {
        name: 'formatDirectedNetwork',
        description: 'formatDirectedNetworkDescription',
        componentName: 'directedNetwork',
        component: directedNetwork,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-r%C3%A9seaux-diriges',
        isUrlValue: false,
    },
    {
        name: 'formatDirected3DNetwork',
        description: 'formatDirected3DNetworkDescription',
        componentName: 'directed3DNetwork',
        component: directed3DNetwork,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-r%C3%A9seaux-diriges-3d',
        isUrlValue: false,
    },
    {
        name: 'formatVenn',
        description: 'formatVennDescription',
        componentName: 'venn',
        component: venn,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-de-venn',
    },
    {
        name: 'formatLeaflet',
        description: 'formatLeafletDescription',
        componentName: 'leaflet',
        component: leaflet,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#carte-leaflet',
    },
    {
        name: 'formatBubbleChart',
        description: 'formatBubbleChartDescription',
        componentName: 'bubbleChart',
        component: bubbleChart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-graphe-%C3%A0-bulles',
        isUrlValue: false,
    },
    {
        name: 'formatRedirect',
        description: 'formatRedirectDescription',
        componentName: 'redirect',
        component: redirect,
        type: 'url',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#url-redirection-automatique',
        isUrlValue: true,
    },
    {
        name: 'formatSparqlTextField',
        description: 'formatSparqlTextFieldDescription',
        componentName: 'sparqlTextField',
        component: sparqlTextField,
        type: 'text',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#sparql-texte',
        isUrlValue: true,
    },
    {
        name: 'formatIstexSummary',
        description: 'formatIstexSummaryDescription',
        componentName: 'istexSummary',
        component: istexSummary,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-sommaire-istex',
        isUrlValue: true,
    },
    {
        name: 'formatStreamgraph',
        description: 'formatStreamgraphDescription',
        componentName: 'streamgraph',
        component: streamgraph,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-graphique-de-flux',
        isUrlValue: false,
    },
    {
        name: 'formatHierarchy',
        description: 'formatHierarchyDescription',
        componentName: 'hierarchy',
        component: hierarchicalTree,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-graphique-hi%C3%A9rarchique',
        isUrlValue: false,
    },
    {
        name: 'formatIstexCitation',
        description: 'formatIstexCitationDescription',
        componentName: 'istexCitation',
        component: istexCitation,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#autre-article-citant',
        isUrlValue: true,
    },
    {
        name: 'formatIstexRefbibs',
        description: 'formatIstexRefbibsDescription',
        componentName: 'istexRefbibs',
        component: istexRefbibs,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/', // format missing from documentation
        isUrlValue: true,
    },
    {
        name: 'formatFlowMap',
        description: 'formatFlowMapDescription',
        componentName: 'flowMap',
        component: flowMap,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/#graphique-cartographie-de-flux',
        isUrlValue: false,
    },
    {
        name: 'formatClusteredChart',
        description: 'formatClusteredChartDescription',
        componentName: 'clusteredChart',
        component: clusteredChart,
        type: 'chart',
        isValueAnnotable: false,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/', // format missing from documentation
        isUrlValue: false,
    },
    {
        name: 'formatJsonDebug',
        description: 'formatJsonDebugDescription',
        componentName: 'json',
        component: json,
        type: 'other',
        isValueAnnotable: true,
        docUrl: 'https://www.lodex.fr/docs/documentation/principales-fonctionnalites-disponibles/appliquer-un-format/', // format missing from documentation
        isUrlValue: true,
    },
    {
        name: 'formatBackButton',
        description: 'backButtonDescription',
        componentName: 'backButton',
        type: 'other',
        component: backButton,
        isValueAnnotable: false,
        docUrl: '',
        isUrlValue: false,
    },
];
