# Reduce to distinct values from one or more fields

prepend = delegate?file=../worker.ini
mimeType = application/json
label = distinct

[use]
plugin = basics
plugin = lodex

[buildContext]
connectionStringURI = get('connectionStringURI')

[env]
; On garde dans l'environnement quelques paramètres
path = field
value = get('field').castArray()

path = minValue
value = env('minValue').parseInt().defaultTo(0)

path = maxValue
value = env('maxValue').parseInt().defaultTo(1000000)

path = maxSize
value = env('maxSize').parseInt().defaultTo(10)

path = sortField
value = env('orderBy', '_id/asc').split('/').get(0)

path = reverse
value = env('orderBy', '_id/asc').split('/').get(1).replace('asc', 1).replace('desc', -1).parseInt()

[singleton]
merge = false
[singleton/LodexEnsureIndex]
field = fix(`lastVersion.${env('field.0')}`)

[LodexAggregateQuery]
stage = fix(`$unwind: "$lastVersion.${env('field.0')}"`)
stage = fix(`$group: {_id: "$lastVersion.${env('field.0')}", value: { $sum: 1 } }`)
stage = fix(`$match: { value: { $gte: ${env('minValue')}, $lte: ${env('maxValue')} } }`)
stage = fix(`$sort: { ${env('sortField')} : ${env('reverse')} }`)
stage = fix(`$skip: 0`)
stage = fix(`$limit:  ${env('maxSize')}`)

[LodexOutput]
indent = true
extract = total

