# Reduce to distinct values from one or more fields

prepend = delegate?file=../worker.ini
mimeType = application/json
label = distinct

[use]
plugin = basics
plugin = lodex

[buildContext]
connectionStringURI = get('connectionStringURI')

[env]
; On garde dans l'environnement quelques paramètres
path = field
value = get('field').castArray()

[singleton]
merge = false
[singleton/LodexEnsureIndex]
field = fix(`lastVersion.${env('field.0')}`)

[LodexAggregateQuery]
stage = fix(`$unwind: "$lastVersion.${env('field.0')}"`)
stage = fix(`$group: {_id: "$lastVersion.${env('field.0')}", value: { $sum: 1 } }`)

[LodexOutput]
indent = true
extract = total

