prepend = delegate?file=../worker.ini
mimeType = application/json
label = like paring-with

[use]
plugin = basics
plugin = lodex

[buildContext]
connectionStringURI = get('connectionStringURI')

[env]
; On garde dans l'environnement quelques paramètres
path = field
value = get('field').castArray()

path = minValue
value = env('minValue').parseInt().defaultTo(0)

path = maxValue
value = env('maxValue').parseInt().defaultTo(1000000)

path = maxSize
value = env('maxSize').parseInt().defaultTo(10)

path = sortField
value = env('orderBy', '_id/asc').split('/').get(0).replace('value', 'weight').replace('id', 'source')

path = reverse
value = env('orderBy', '_id/asc').split('/').get(1).replace('asc', 1).replace('desc', -1).parseInt()

[singleton]
merge = false
[singleton/LodexEnsureIndex]
field = fix(`lastVersion.${env('field.0')}`)

[LodexAggregateQuery]
stage = fix(`$project: { "pairs": { $reduce: { "input": "$lastVersion.${env('field.0')}", "initialValue": [], "in": { $concatArrays: [ "$$value", { $map: { "input": "$lastVersion.${env('field.1')}", "as": "x", "in": { "source": "$$this", "target": "$$x" } } } ] } } } }`)
stage = fix(`$unwind: "$pairs"`)
stage = fix(`$group: { "_id": { "source": "$pairs.source", "target": "$pairs.target" }, "weight": { $sum: 1 } }`)
stage = fix(`$match: { weight: { $gte: ${env('minValue')}, $lte: ${env('maxValue')} } }`)
stage = fix(`$sort: { ${env('sortField')} : ${env('reverse')} }`)
stage = fix(`$skip: 0`)
stage = fix(`$limit:  ${env('maxSize')}`)


[replace]
path = source
value = get('_id.source')
path = target
value = get('_id.target')
path = weight
value = get('weight')


[LodexOutput]
indent = true
extract = total

