# For one document selected by a URI (otherwise the first of the stream),
# and with one field on parameter, we build a vector from the initial document
# and all documents that shared one or more values of the field
#
# Be carful :  works only with @ezs/lodex > 1.0.1
prepend = delegate?file=../worker.ini
mimeType = application/json
label = similar-by

[use]
plugin = basics
plugin = lodex
plugin = analytics

[env]
path = database_url
value = http://qdrant.lodex-net:6333


path = connectionStringURI
value = get('connectionStringURI')

[buildContext]
connectionStringURI = env('connectionStringURI')

; On garde dans l'environnement quelques paramètres
[env]
path = minValue
value = env('minValue').split('§').map(parseFloat).shift().defaultTo(0)

path = maxValue
value = env('maxValue').split('§').map(parseFloat).shift().defaultTo(1)

path = maxSize
value = env('maxSize').parseInt().defaultTo(10)

path = reverse
value = env('orderBy').split('/').get(1).replace('asc', 0).replace('desc', 1).parseInt()

path = uri
value = get('filter.uri')

path = fields
value = get('fields')

path = field
value = get('field').castArray()


; On récupére les documents filtrés
[LodexRunQuery]

; On supprime les infos inutiles
[filterVersions]
[filterContributions]

[shift]

[multiply]
path = key
value = env('field').compact().filter(x => typeof x === 'string')

[assign]
path = id
value = get('uri')

path = value
value = get(self.key)

# Préparation de la requete de rapprochement
[replace]
path = query
value = get('value')

path = limit
value = env('maxSize')

path = with_payload
value = false

[createVectorEmbeddings]
path = query


[spawn]
[spawn/debug]
text = env('database_url').append('/collections/ma_collection/points/query').prepend('POST ')
[spawn/URLConnect]
url = env('database_url').append('/collections/ma_collection/points/query')
method = POST
json = true
streaming = true
encoder = pack
noerror = true
timeout = 30000
[spawn/debug]
text = resulat similarité


[exchange]
value = get('points')

[ungroup]

[greater]
path = score
than = 0.5
[remove]
test = get('score').gt(1) ; ne marche pas tout le temps

[decode]
path = id
mode = uuid

[debug]
text = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[exchange]
value = get('id')
[group]
size = env('maxSize')

; Create mongodb filter (@TODO Change versions to a dynamic call when needed)
[replace]
path = filter.uri.$in
value = self()

[debug]
text = value

; Get filtered data
[LodexRunQuery]
sortOn = get(`ref_field.${self.sortOn}`)
sortOrder = env('sortOrder')

; Remove useless data
[filterVersions]
[filterContributions]

; find the fields which are selected for title and summary
[assign]
path = titleFieldName
value = env('fields').find({'overview':1}).get('name')

path = summaryFieldName
value = env('fields').find({'overview':2}).get('name')

path = detail1FieldName
value = env('fields').find({'overview':3}).get('name')

path = detail2FieldName
value = env('fields').find({'overview':4}).get('name')

path = subtitleFieldName
value = env('fields').find({'overview':6}).get('name')

path = host
value = env('host')

[assign]
path = id
value = get('uri')

path = title
value = get(self.titleFieldName).toString()

path = summary
value = get(self.summaryFieldName).toString()

path = detail1
value = get(self.detail1FieldName).toString()

path = detail2
value = get(self.detail2FieldName).toString()

path = subtitle
value = get(self.subtitleFieldName).toString()

path = date_published
value = get('publicationDate')

path = url
value = pick(['host', 'uri']).values().join('/')

; Send only a part of the data
[slice]
start = 1
size = env('maxSize')

; Keep only the necessary data
[keep]
path = id
path = url
path = title
path = summary
path = detail1
path = detail2
path = subtitle
path = date_published
path = total


; Create and structured output
[LodexOutput]
keyName = items
indent = true
extract = total
