prepend = delegate?file=../worker.ini
mimeType = application/json
label = Pre-calculation for vectors search

[use]
plugin = basics
plugin = lodex

[env]
path = connectionStringURI
value = get('connectionStringURI')

[buildContext]
connectionStringURI = env('connectionStringURI')
tenant =  get('tenant')
precomputedName =  get('precomputedName')

[assign]
path = queryVector
value = get('filter.$text.$search').defaultTo('a')

[createVectorEmbeddings]
path = queryVector

[runVSearchPrecomputed]
valueFieldName = env('precomputedValueColumn').defaultTo('value')
labelFieldName = env('precomputedLabelColumn').defaultTo('id')

[exchange]
value = self().omit(['origin', 'documents'])

[injectSyndicationFrom]
connectionStringURI = env('connectionStringURI')
path = id

; Send only a part of the data
[slice]
start = 1
size = env('maxSize')

; find the fields which are selected for title and summary
[assign]
path = title
value = get('id_title')

path = summary
value = get('id_summary')

path = detail1
value = get('id_detail1')

path = detail2
value = get('id_detail2')

path = subtitle
value = get('id_subtitle')

path = date_published
value = get('publicationDate')

path = url
value = env('host').concat('/').concat(self.id)

; Create and structured output
[LodexOutput]
keyName = items
indent = true
extract = total

