prepend = delegate?file=../worker.ini
mimeType = application/json
label = vsearch-precomputed

[use]
plugin = basics
plugin = lodex

; On garde dans l'environment quelques variables issues de la config Lodex
[config2env]
path = tdmservices

; On garde dans l'environment quelques variables issues de la query url
[env]
path = connectionStringURI
value = get('connectionStringURI')

; On crée à partir de la query url un objet plus riche avec tout le context lodex
[buildContext]
connectionStringURI = env('connectionStringURI')
tenant =  get('tenant')
precomputedName =  get('precomputedName')

; On garde dans l'environment quqleques variables issues du context Lodex
[env]
path = total
value = get('total').parseInt().defaultTo(0)

path = minValue
value = env('minValue').parseInt().defaultTo(0)

path = maxValue
value = env('maxValue').parseInt().defaultTo(1000000)

path = maxSize
value = env('maxSize').parseInt().defaultTo(10)

path = reverse
value = env('orderBy').split('/').get(1).replace('asc', 1).replace('desc', 0).parseInt()

path = tuneBy
value = env('orderBy').split('/').get(0).replace('_id', 'id')

path = fields
value = get('fields')

path = textFields
value = get('fields').filter({searchable: true}).map('name')

path = nameFields
value = get('fields').map('name')

path = labelFields
value = get('fields').map('label')

path = queryVector
value = get('filter.$text.$search').defaultTo('')

path = host
value = get('host')

; -----------------------------------------------------------------------------
; On lance la recherche de vector dans la base
; On commence par vectoriser la question  avec le ws d'embedding
[assign]
path = queryVector
value = env('queryVector')

[remove]
test = get('queryVector').isEmpty()

; appel du ws sur le champ queryVector
[expand]
path = queryVector
size = 1
; We avoid recalculating identical queries
cacheName = embedding

[expand/URLConnect]
url = env('tdmservices.embedding.url')
timeout = env('tdmservices.embedding.timeout')  
noerror = false

; le ws renvoit plusieurs champs on en garde qu'un 
[expand/replace]
path = id 
value = get('id')
path = value
value = get('value.vector')

; et une fois transformé en vecteur 
; on recherche les vecteurs proches dans la base
[runVSearchPrecomputed]
valueFieldName = env('precomputedValueColumn').defaultTo('value')
labelFieldName = env('precomputedLabelColumn').defaultTo('id')
dimensions = env('tdmservices.embedding.dimensions')
threshold = env('tdmservices.embedding.threshold')

[debug]
text = Documents trouvés dans la base

; -----------------------------------------------------------------------------
; On reformate la sortie à partir des schemes 
; pour créer un flux compatible avec le service de rerank
[replace]
path = metadata
value = get('documents').find({ 'uri': self.id }).get('lastVersion')

path = id
value = get('id')

path= uri
value = get('id')

path = value
value = get('value')

path = total
value = get('total')


; Création d'un texte compatible avec les IA 
[assign]
path = text
value = get('metadata').pick(env('textFields'))

[keyMapping]
path = text
from = env('nameFields')
to = env('labelFields')

[assign]
path = text
value = get('text').reduce((accumulator, value, key) => accumulator.concat(`# ${key} :\n${_.toString(value)}\n\n`))

; on tranforme les identifiants techniques en champs labelisés en fonction des schemes souhaités
[semanticMapping]
path = metadata
fields = env('fields')

from = http://purl.org/dc/terms/title
to = titre

from = http://purl.org/dc/terms/creator
to = auteurs

from = http://purl.org/dc/terms/date
to = date_publication

from = http://purl.org/ontology/bibo/journal
to = journal

from = http://purl.org/ontology/bibo/volume
to = volume

from = http://purl.org/ontology/bibo/issue
to = numero

from = http://purl.org/ontology/bibo/pages
to = pages

from = http://purl.org/ontology/bibo/doi
to = doi

from = http://purl.org/dc/terms/language
to = langue

from = http://purl.org/dc/terms/subject
to = mots_cles

from = http://purl.org/dc/terms/type
to = type_document

from = http://schema.org/accessMode
to = acces

from = http://purl.org/ontology/bibo/collection
to = corpus

from = http://purl.org/dc/terms/abstract
to = resume

; rerank demande tous les documents dans le champ value
; On prend uniqument les N premiers résulats 
; pour créer le fux compatible
[group]
length = env('maxSize')

[shift]

; on crée les 3 chamsp obligatoire demandé par rerank
[replace]
path = value.documents
value = self()
path = value.question
value = env('queryVector')
path = value.top_n
value = env('tdmservices.rerank.size')

; appel du ws sur le champ value
[expand]
path = value
size = 1

[expand/URLConnect]
url = env('tdmservices.rerank.url')
timeout = env('tdmservices.rerank.timeout')
noerror = false

; rerank renvoit plusieurs champs on ne prend que celui contenant les résulats
[expand/replace]
path = id 
value = get('id')
path = value
value = get('value.documents').map((value, index, collection)=>({...value, total: collection.length}))

; On tranforme le tableau de résulats pour traiter chaque document séparément
[ungroup]
path = value

; A partir de l'identifiant du docyment on crée un flux avec 
; les informations de syndication de chaque document (titre, detail1, detail2, etc.)
[injectSyndicationFrom]
connectionStringURI = env('connectionStringURI')
path = id

; On reformate la sortie produite par injectSyndicationFrom
; pour obtnir un flux compatible avec les "formats" lodex 
[replace]
path = id	
value = get('id')

path = value
value = get('value')

path = title
value = get('id_title')

path = summary
value = get('id_summary')

path = detail1
value = get('id_detail1')

path = detail2
value = get('id_detail2')

path = subtitle
value = get('id_subtitle')

path = date_published
value = get('publicationDate')

path = url
value = env('host').concat('/').concat(self.id)

path = total
value = get('total')

; On produit un format de sortie standard pour Lodex
[LodexOutput]
keyName = items
indent = true
extract = total

