# For one document selected by a URI (otherwise the first of the stream),
# and with one field on parameter, we build a vector from the initial document
# and all documents that shared one or more values of the field
#
# Be carful :  works only with @ezs/lodex > 1.0.1
prepend = delegate?file=../worker.ini
mimeType = application/json
label = similar-by

[use]
plugin = basics
plugin = lodex
plugin = analytics

; On garde dans l'enviornnment quelques variables issues de la config Lodex
[config2env]
path = tdmservices

; On garde dans l'environnement quelques paramètres passé dans l'URL
[env]
path = connectionStringURI
value = get('connectionStringURI')

path = precomputedName
value = get('precomputedName')

path = minValue
value = env('minValue').split('§').map(parseFloat).shift().defaultTo(0)

path = maxValue
value = env('maxValue').split('§').map(parseFloat).shift().defaultTo(1)

path = maxSize
value = env('maxSize').parseInt().defaultTo(10)

path = reverse
value = env('orderBy').split('/').get(1).replace('asc', 0).replace('desc', 1).parseInt()

; A partir des paramètres de l'ULR on construit un object permettant de faire une recherche dans la base mongoDB 
[buildContext]
connectionStringURI = env('connectionStringURI')

; On garde dans l'environnement quelques élements produit pas buildContext
[env]
path = uri
value = get('filter.uri')

path = fields
value = get('fields')

path = field
value = get('field').castArray()

path = titleFieldName
value = get('fields').find({'overview':1}).get('name')

path = summaryFieldName
value = get('fields').find({'overview':2}).get('name')

path = detail1FieldName
value = get('fields').find({'overview':3}).get('name')

path = detail2FieldName
value = get('fields').find({'overview':4}).get('name')

path = subtitleFieldName
value = get('fields').find({'overview':6}).get('name')

; On récupére les documents filtrés (ici on doit trouvé uniqument un document avec son uri)
[LodexRunQuery]

; On supprime les infos inutiles
[filterVersions]
[filterContributions]

# On prend uniqument le premier (c'est une sécurité car normalement le nombre de résulat de la requete est 0 ou 1)
[shift]

# Préparation de la requete de rapprochement
[replace]

; On prend le titre du document comme requete pour trouver les documents similaires
path = queryVector
value = get(env('titleFieldName')).toString()

path = connectionStringURI
value = env('connectionStringURI')

path = referer.id
value = get('uri')

path = referer.value
value = get('value')

path = referer.key
value = env('field.0')

[assign]
path = filter.uri.$ne
value = get('referer.id')

; On encode le champ contenant une requete en vecteur
[expand]
path = queryVector
size = 1
cacheName = embedding

[expand/URLConnect]
url = env('tdmservices.embedding.url')
timeout = 5000
noerror = false

[expand/replace]
path = id 
value = get('id')
path = value
value = get('value.vector')

; On lance la requete de recherche de vecteur dans MongoT
[runVSearchPrecomputed]
precomputedName = env('precomputedName')
dimensions = env('tdmservices.embedding.dimensions')

; On garde uniqument les document dont la similarité sémantique est supérieur à 80%
[greater]
than = 0.8

; On s'assure de renvoyer le nombre maximun de documents demandés
[slice]
start = 1
size = env('maxSize')

; Remove useless data
[filterVersions]
[filterContributions]

; Séries d'instruction pour refomater le JSON
[assign]
path = uri
value = get('id')

path = host
value = env('host')

[assign]
path = title
value = get('documents.0.lastVersion').get(env('titleFieldName')).toString()

path = summary
value = get('documents.0.lastVersion').get(env('summaryFieldName')).toString()

path = detail1
value = get('documents.0.lastVersion').get(env('detail1FieldName')).toString()

path = detail2
value = get('documents.0.lastVersion').get(env('detail2FieldName')).toString()

path = subtitle
value = get('documents.0.lastVersion').get(env('subtitleFieldName')).toString()

path = date_published
value = get('documents.0.lastVersion').get('publicationDate')

path = url
value = pick(['host', 'uri']).values().join('/')

; Keep only the necessary data
[keep]
path = id
path = url
path = title
path = summary
path = detail1
path = detail2
path = subtitle
path = date_published
path = total

; Create and structured output
[LodexOutput]
keyName = items
indent = true
extract = total
