name: "✨ Feature"
description: Une demande, une idée ou une nouvelle fonctionnalité.
labels: ["type: feature"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: Motivation & Cas d'usage
      description: Détaillez les limites de l'implémentation actuelle et la valeur ajoutée de cette évolution pour un type d'utilisateur.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution Proposée
      description: Décrivez brièvement comment vous imaginez cette fonctionnalité.
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - Basse
        - Moyenne
        - Haute
