syncSource:
  replicaSet:
    hostAndPort:
      - "mongod.lodex-net:27017"

    scramAuth:
      username: mongotUser
      authSource: admin
      passwordFile: /mongot-community/pwfile
      tls:
        enabled: false

storage:
  dataPath: "/data/mongot"

server:
  grpc:
    address: "mongot.lodex-net:27028"
    tls:
      mode: disabled

metrics:
  enabled: false
  address: "mongot.lodex-net:9946"

healthCheck:
  address: "mongot.lodex-net:8080"

logging:
  verbosity: INFO
