import { DEFAULT_TENANT } from '@lodex/common';
import config from 'config';
import { MongoClient, type Db } from 'mongodb';
import getLogger from './logger';
import ConnectionString from 'mongodb-connection-string-url';

/**
 * @type {Map<string, MongoClient>}
 */
const clients = new Map();

export const mongoConnectionString = (tenant?: string) => {
    if (process.env.NODE_ENV === 'test' && process.env.MONGODB_URI_FOR_TESTS) {
        // URI generated by Jest. see jest-mongodb-config.js
        return process.env.MONGODB_URI_FOR_TESTS;
    }
    const cs = new ConnectionString(config.get('mongo.uri'));
    if (config.has('mongo.host')) {
        cs.hosts = [].concat(config.get('mongo.host'));
    }
    if (config.has('mongo.dbName')) {
        cs.pathname = config.get('mongo.dbName')
    }
    cs.pathname = `${cs.pathname}_${tenant || DEFAULT_TENANT}`;
    return cs.toString();
}

/**
 * Get the DBMS client
 * @param tenant Name of the Lodex instance
 * @returns {Promise<MongoClient>}
 */
const mongoClientConnectionFactory = async (tenant: string) => {
    if (!tenant) {
        throw new Error(
            `L'instance n'est pas renseigné, impossible de se connecter à la base de données.`,
        );
    }

    if (clients.has(tenant)) {
        return clients.get(tenant);
    }

    const cnxstr = mongoConnectionString(tenant);
    try {
        const client = new MongoClient(cnxstr, {
            maxPoolSize: 10,
            authSource: 'admin',
        });
        clients.set(tenant, await client.connect());
        return client;
    } catch (error) {
        const logger = getLogger(tenant);
        logger.error(error);
        throw new Error(
            `L'url de la base mongoDB n'est pas bonne, ou non renseignée. ${cnxstr}`,
        );
    }
};

export const mongoClientFactory = async (tenant: string): Promise<Db> => {
    return (await mongoClientConnectionFactory(tenant)).db();
};

export const closeDb = async (tenant: string) => {
    if (clients && clients.has(tenant)) {
        await clients.get(tenant).close();
    }
};

export type MongoClientFactory = typeof mongoClientFactory;

export default mongoClientFactory;
