// node-config use CJS see https://github.com/node-config/node-config/wiki/Special-features-for-JavaScript-configuration-files

const path = require('node:path');
const dotenv = require('dotenv');

const envname = path.resolve(__dirname, '../config.env');
const result = dotenv.config({
    path: envname,
    quiet: false,
});
if (result.error) {
    console.warn(`Unable to parse ${envname} `);
    throw result.error;
}
const [host, port] = String(process.env.MAILER_HOST || 'localhost:1025').split(
    ':',
);
module.exports = {
    port: 3000,
    mongo: {
        host: process.env.MONGO_HOST,
        dbName: 'lodex',
    },
    rootAuth: {
        username: process.env.ROOT_LOGIN,
        password: process.env.ROOT_PASSWORD,
    },
    auth: {
        cookieSecret: 'cookie',
        headerSecret: 'header',
        expiresIn: 10 * 3600, // 10 hours
    },
    cache: {
        max: 500,
        maxAge: 60 * 60, // 1 hour
    },
    hostname: 'http://data.istex.fr/',
    uploadDir: 'upload',
    istexApiUrl: 'https://api.istex.fr',
    jsHost: '',
    jsHosts: {
        rootAdmin: '',
        admin: '',
        public: '',
    },
    themesHost: '',
    logger: {
        disabled: false,
    },
    ezs: {
        verbose: 'ezs:*,-ezs:debug',
        timeout: 12000,
        cacheEnable: false,
        cacheDelay: 60 * 60 * 12,
        mainStatement: 'delegate',
        encoding: '',
    },
    timeout: 3600000,
    alternativePrecomputedBaseUrl: process.env.PRECOMPUTED_URL,
    activateBullDashboard: false,
    mail: {
        host,
        port: Number(port),
        from: 'noreply@inist.fr',
    },
    themes: [
        'voscouleurs',
        'void',
        'nougat',
        'inist',
        'hal-cnrs',
        'istex',
        'istex-legacy',
        'default',
    ],
    scripts: {
        routines: [
            'all-documents',
            'classif-by',
            'close-by',
            'count-all',
            'count-by-fields',
            'count-distinct-by',
            'cross-by',
            'decompose-by',
            'distance-with',
            'distinct-alpha-2-alpha3-from',
            'distinct-alpha-3-alpha2-from',
            'distinct-alpha-3-ISO3166-1-from',
            'distinct-alpha-3-ISO639-from',
            'distinct-by-field',
            'distinct-by',
            'hierarchy-by',
            'ventilate-by',
            'distinct-ISO3166-1-alpha2-from',
            'distinct-ISO3166-1-alpha3-from',
            'distribute-by-date',
            'distribute-by-decadal',
            'distribute-by-interval',
            'filter',
            'get-fields',
            'graph-by',
            'segments-precomputed',
            'segments-precomputed-nofilter',
            'values-precomputed',
            'values-precomputed-nofilter',
            'raw-precomputed-nofilter',
            'group-and-sum-with',
            'hello-world',
            'istex-facet',
            'labeled-resources',
            'pairing-with',
            'percentage-of',
            'refs',
            'select-by',
            'sitemap',
            'sparql-query',
            'sub-resources-asterplot',
            'sub-resources-co-occurrences',
            'syndication-from',
            'syndication',
            'total-of',
            'tree-by',
            'unwind-by',
        ],
        loaders: [
            'bib',
            'csv',
            'csv-semicolon',
            'csv-comma',
            'tsv',
            'tsv-double-quotes',
            'tsv-wos',
            'rdf',
            'skos',
            'json',
            'json-annotations',
            'json-conditor',
            'json-import',
            'json-istex',
            'json-lodex',
            'json-wordpress',
            'json-datacite',
            'json-openalex',
            'json-inspirehep',
            'json-optimized',
            'json-lines',
            'query-istex',
            'query-conditor',
            'query-conditor-for-halcnrs',
            'query-openalex',
            'rss',
            'atom',
            'mods',
            'tei',
            'tei-persee',
            'xml',
            'corpus',
            'zip',
            'doi-list',
            'tar-gz',
        ],
        exporters: ['csv', 'csv-full', 'json', 'tsv', 'tsv-full'],
    },
};
