const ezs = require('@ezs/core');
const from = require('from');

describe('json-conditor.ini', () => {
    it('should parse a JSON', done => {
        const res = [];
        const expected = [
            {
                "abstract en": "1. abstract.en",
                "abstract fr": "",
                "articleNumber": "",
                "arxiv": "",
                "authors affiliations address": "[[\"address A1\"],[\"address B1\",\"address B2\"]]",
                "authors affiliations idRef": "[[null],[null,null]]",
                "authors affiliations isni": "[[null],[null,null]]",
                "authors affiliations ref": "[[null],[null,null]]",
                "authors affiliations rnsr": "[[null],[null,null]]",
                "authors enrichments idHal": "[null,null]",
                "authors enrichments idRef": "[null,null]",
                "authors enrichments orcId": "[null,null]",
                "authors forename & authors surname": "[\"forename A surname A\",\"forename B surname B\"]",
                "authors halAuthorId": "[null,null]",
                "authors idHal": "[null,null]",
                "authors idRef": "[null,null]",
                "authors isni": "[null,null]",
                "authors orcId": "[null,null]",
                "authors researcherId": "",
                "authors viaf": "",
                "bibCode": "",
                "cern": "",
                "classification dewey": "",
                "classification hal": "",
                "classification tef": "",
                "classification thesisDomain": "",
                "creationDate": "",
                "defenseOrganisms associatedLaboratory": "[]",
                "defenseOrganisms associatedLaboratoryIdRef": "[]",
                "defenseOrganisms degreeGrantor": "[]",
                "defenseOrganisms degreeGrantorIdRef": "[]",
                "defenseOrganisms doctoralSchool": "[]",
                "defenseOrganisms doctoralSchoolIdRef": "[]",
                "documentType": "",
                "doi": "[\"doi1\"]",
                "duplicateRules": "",
                "duplicates source": "[null,null]",
                "duplicates sourceUid": "[\"sourceUid1\",\"sourceUid2\"]",
                "eisbn": "",
                "eissn": "",
                "electronicPublicationDate": "",
                "enrichments classifications bso": "",
                "enrichments classifications scienceMetrix level": "[1,2]",
                "enrichments classifications scienceMetrix value": "[\"value1\",\"value2\"]",
                "enrichments classifications scopus level": "[]",
                "enrichments classifications scopus value": "[]",
                "enrichments oa core": "",
                "enrichments oa unpaywall": "",
                "ensam": "",
                "fulltextPath": "",
                "funders grantNumber": "[]",
                "funders name": "[]",
                "halId": "",
                "hasDoi": "",
                "hasFulltext": "",
                "hasTransDuplicate": "",
                "idChain": "",
                "idConditor": "",
                "idProdinra": "",
                "ineris": "",
                "inspire": "",
                "ird": "",
                "irstea": "",
                "isDeduplicable": "",
                "isDuplicate": "",
                "isNearDuplicate": "",
                "isbn": "",
                "issn": "",
                "issue": "",
                "keywords en author": "",
                "keywords en mesh": "",
                "keywords fr author": "",
                "keywords fr mesh": "",
                "keywords fr rameau": "",
                "language": "",
                "localRef": "",
                "meetingAbstractNumber": "",
                "nearDuplicates source": "[]",
                "nearDuplicates sourceUid": "[]",
                "nearDuplicatesDetectedBySimilarity source": "[]",
                "nearDuplicatesDetectedBySimilarity sourceUid": "[]",
                "nnt": "",
                "oatao": "",
                "okina": "",
                "otherNumber": "",
                "pageRange": "",
                "part": "",
                "patentNumber": "",
                "path": "",
                "pii": "",
                "pmId": "",
                "pmc": "",
                "ppn": "",
                "publicationDate": "",
                "publisher": "",
                "reportNumber": "",
                "sciencespo": "",
                "sessionName": "",
                "source": "",
                "sourceId": "",
                "sourceUid": "",
                "specialIssue": "",
                "supplement": "",
                "thesisAdvisor forename": "[]",
                "thesisAdvisor idRef": "[]",
                "thesisAdvisor surname": "[]",
                "title default": "",
                "title en": "",
                "title fr": "",
                "title journal": "",
                "title meeting": "",
                "title monography": "",
                "typeConditor": "",
                "utKey": "",
                "volume": ""
            },
            {
                "abstract en": "2. abstract.en",
                "abstract fr": "",
                "articleNumber": "",
                "arxiv": "",
                "authors affiliations address": "[[\"address C1\"],[\"address D1\",\"address D2\"]]",
                "authors affiliations idRef": "[[null],[null,null]]",
                "authors affiliations isni": "[[null],[null,null]]",
                "authors affiliations ref": "[[null],[null,null]]",
                "authors affiliations rnsr": "[[null],[null,null]]",
                "authors enrichments idHal": "[null,null]",
                "authors enrichments idRef": "[null,null]",
                "authors enrichments orcId": "[null,null]",
                "authors forename & authors surname": "[\"forename C surname C\",\"forename D surname D\"]",
                "authors halAuthorId": "[null,null]",
                "authors idHal": "[null,null]",
                "authors idRef": "[null,null]",
                "authors isni": "[null,null]",
                "authors orcId": "[null,null]",
                "authors researcherId": "",
                "authors viaf": "",
                "bibCode": "",
                "cern": "",
                "classification dewey": "",
                "classification hal": "",
                "classification tef": "",
                "classification thesisDomain": "",
                "creationDate": "",
                "defenseOrganisms associatedLaboratory": "[]",
                "defenseOrganisms associatedLaboratoryIdRef": "[]",
                "defenseOrganisms degreeGrantor": "[]",
                "defenseOrganisms degreeGrantorIdRef": "[]",
                "defenseOrganisms doctoralSchool": "[]",
                "defenseOrganisms doctoralSchoolIdRef": "[]",
                "documentType": "",
                "doi": "[\"doi2\"]",
                "duplicateRules": "",
                "duplicates source": "[null,null]",
                "duplicates sourceUid": "[\"sourceUid1\",\"sourceUid2\"]",
                "eisbn": "",
                "eissn": "",
                "electronicPublicationDate": "",
                "enrichments classifications bso": "",
                "enrichments classifications scienceMetrix level": "[]",
                "enrichments classifications scienceMetrix value": "[]",
                "enrichments classifications scopus level": "[]",
                "enrichments classifications scopus value": "[]",
                "enrichments oa core": "",
                "enrichments oa unpaywall": "",
                "ensam": "",
                "fulltextPath": "",
                "funders grantNumber": "[]",
                "funders name": "[]",
                "halId": "",
                "hasDoi": "",
                "hasFulltext": "",
                "hasTransDuplicate": "",
                "idChain": "",
                "idConditor": "",
                "idProdinra": "",
                "ineris": "",
                "inspire": "",
                "ird": "",
                "irstea": "",
                "isDeduplicable": "",
                "isDuplicate": "",
                "isNearDuplicate": "",
                "isbn": "",
                "issn": "",
                "issue": "",
                "keywords en author": "",
                "keywords en mesh": "",
                "keywords fr author": "",
                "keywords fr mesh": "",
                "keywords fr rameau": "",
                "language": "",
                "localRef": "",
                "meetingAbstractNumber": "",
                "nearDuplicates source": "[]",
                "nearDuplicates sourceUid": "[]",
                "nearDuplicatesDetectedBySimilarity source": "[]",
                "nearDuplicatesDetectedBySimilarity sourceUid": "[]",
                "nnt": "",
                "oatao": "",
                "okina": "",
                "otherNumber": "",
                "pageRange": "",
                "part": "",
                "patentNumber": "",
                "path": "",
                "pii": "",
                "pmId": "",
                "pmc": "",
                "ppn": "",
                "publicationDate": "",
                "publisher": "",
                "reportNumber": "",
                "sciencespo": "",
                "sessionName": "",
                "source": "",
                "sourceId": "",
                "sourceUid": "",
                "specialIssue": "",
                "supplement": "",
                "thesisAdvisor forename": "[]",
                "thesisAdvisor idRef": "[]",
                "thesisAdvisor surname": "[]",
                "title default": "",
                "title en": "",
                "title fr": "",
                "title journal": "",
                "title meeting": "",
                "title monography": "",
                "typeConditor": "",
                "utKey": "",
                "volume": ""
            }
        ];
        const input = [
            {
                "abstract":{"en": "1. abstract.en"},
                "authors":[
                    {
                        "forename": "forename A",
                        "surname": "surname A",
                        "affiliations": [{"address": "address A1"}]
                    },
                    {
                        "forename": "forename B",
                        "surname": "surname B",
                        "affiliations": [{"address": "address B1"}, {"address": "address B2"}]
                    }
                ],
                "doi":["doi1"],
                "duplicates":[
                    {"sourceUid": "sourceUid1"},
                    {"sourceUid": "sourceUid2"}
                ],
                "enrichments":{
                    "classifications":{
                        "scienceMetrix":[
                        {"level": 1, "value": "value1"},
                        {"level": 2, "value": "value2"}
                        ]
                    }
                }
            },
            {
                "abstract":{"en": "2. abstract.en"},
                "authors":[
                    {
                        "forename": "forename C",
                        "surname": "surname C",
                        "affiliations": [{"address": "address C1"}]
                    },
                    {
                        "forename": "forename D",
                        "surname": "surname D",
                        "affiliations": [{"address": "address D1"}, {"address": "address D2"}]
                    }
                ],
                "doi":["doi2"],
                "duplicates":[
                    {"sourceUid": "sourceUid1"},
                    {"sourceUid": "sourceUid2"}
                ]
            }
        ];
        from([JSON.stringify(input)])
            .pipe(ezs('delegate', { file: __dirname + '/json-conditor.ini' }))
            .on('data', chunk => {
                res.push(chunk);
            })
            .on('end', () => {
                expect(res).toEqual(expected);
                done();
            });
    });
});
