export type ProgressStatusType =
    | 'PENDING'
    | 'ERROR'
    | 'PUBLISH_FACET'
    | 'PUBLISH_DOCUMENT'
    | 'ENRICHING'
    | 'PRECOMPUTING'
    | 'UNPUBLISH_DOCUMENT'
    | 'UPLOADING_DATASET'
    | 'SAVING_DATASET'
    | 'STARTING'
    | 'CREATE_INDEX'
    | 'INITIALIZING_URI'
    | 'INDEXATION';

export const ProgressStatus = {
    PENDING: 'PENDING',
    ERROR: 'ERROR',
    PUBLISH_FACET: 'PUBLISH_FACET',
    PUBLISH_DOCUMENT: 'PUBLISH_DOCUMENT',
    ENRICHING: 'ENRICHING',
    PRECOMPUTING: 'PRECOMPUTING',
    UNPUBLISH_DOCUMENT: 'UNPUBLISH_DOCUMENT',
    UPLOADING_DATASET: 'UPLOADING_DATASET',
    SAVING_DATASET: 'SAVING_DATASET',
    STARTING: 'STARTING',
    CREATE_INDEX: 'CREATE_INDEX',
    INITIALIZING_URI: 'INITIALIZING_URI',
    INDEXATION: 'INDEXATION',
} as const;
