export const PENDING = 'PENDING';
export const ERROR = 'ERROR';
export const PUBLISH_FACET = 'PUBLISH_FACET';
export const PUBLISH_DOCUMENT = 'PUBLISH_DOCUMENT';
export const UPLOADING_DATASET = 'UPLOADING_DATASET';
export const SAVING_DATASET = 'SAVING_DATASET';
export const STARTING = 'STARTING';
